# Generated by Django 5.1.3 on 2024-11-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costexplorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='aws_account',
            field=models.CharField(max_length=25),
        ),
    ]
